apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egress-updater
rules:
- apiGroups:
  - network.openshift.io
  resources:
  - egressnetworkpolicies
  verbs:
  - '*'
- apiGroups:
  - k8s.ovn.org
  resources:
  - EgressFirewall
  verbs:
  - '*'