kind: CronJob
apiVersion: batch/v1
metadata:
  name: egress-updater
  namespace: egress-test
spec:
  schedule: '*/2 * * * *'
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: egress-updater
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - resources:
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: DIR
                  value: /egress/domains
                - name: WRITE
                  value: /egress/egress_fw.json
              requests:
                cpu: 10m
                memory: 80Mi
              terminationMessagePath: /dev/termination-log
              name: egress-updater
              command:
                - /bin/sh
                - '-ec'
                - '${DIR}/scripts/egress_fw.py && oc apply -f ${DIR}/egress_fw.json'
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: workdir
                  mountPath: /egress
                - name: egress-update-script
                  mountPath: /egress/scripts
                - name: egress-update-domains
                  mountPath: /egress/domains
              terminationMessagePolicy: File
              image: openshift4/ose-cli
          serviceAccount: egress-updater
          volumes:
            - name: workdir
              emptydir: {}
            - name: egress-update-script
              configMap:
                name: egress-update-script
                defaultMode: 0755
            - name: egress-update-domains
              configMap:
                name: egress-update-domains
                defaultMode: 0644
          dnsPolicy: ClusterFirst
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2